# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkingRx2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for NetworkingRx2

end
